export const AppConfig = {
  site_name: 'BlackShore Technology',
  title: 'BlackShore',
  gtm_id: 'G-X1SCDHVLVS',
  description: 'We turn your big ideas into reality',
  locale: 'en',
  technologies: [
    'react',
    'nextjs',
    'javascript',
    'django',
    'fastapi',
    'python',
    'rust',
    'oracle',
    'postgresql',
    'mongodb',
    'kafka',
    'mysql',
    'aws',
  ],
};
